# Generated by Django 5.2.5 on 2025-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='color'),
        ),
    ]
